import {
  type DynamoDBDocumentClient,
  GetCommand,
  PutCommand,
} from "@aws-sdk/lib-dynamodb";
import { v4 as uuidv4 } from "uuid";
import type winston from "winston";
import type User from "../../auth/User.ts";
import type { ConfigOptions } from "../../config/index.ts";
import type { CoreCradle } from "../../container/Cradle.ts";
import type ImageMetadataEntity from "./ImageMetadataEntity.ts";

/** Handle database layer interactions */
export default class ImageMetadataRepository {
  private logger: winston.Logger;
  protected config: ConfigOptions;
  protected dynamoDBDocumentClient: DynamoDBDocumentClient;

  constructor({ loggerProvider, config, dynamoDBDocumentClient }: CoreCradle) {
    this.config = config;
    this.dynamoDBDocumentClient = dynamoDBDocumentClient;
    this.logger = loggerProvider.provide("ImageMetadataRepository");
  }

  /** Submit an image request to the job queue */
  public async insert(prompt: string, user: User) {
    const image: ImageMetadataEntity = {
      imageId: uuidv4(),
      prompt: prompt,
      userId: user.id,
      email: user.email,
      requestedAt: new Date(),
      completedAt: null,
    };
    this.logger.info("insert", { image });

    const dynamoItem = this.toDynamoItem(image);
    const command = new PutCommand({
      TableName: this.config.imageMetadataTableName,
      Item: dynamoItem,
    });
    await this.dynamoDBDocumentClient.send(command);

    return image;
  }

  /** Converts an ImageMetadataEntity to a DynamoDB Item */
  private toDynamoItem(imageMetadata: ImageMetadataEntity) {
    const completedAt =
      imageMetadata.completedAt === null
        ? null
        : imageMetadata.completedAt.toISOString();

    return {
      imageId: imageMetadata.imageId,
      prompt: imageMetadata.prompt,
      userId: imageMetadata.userId,
      email: imageMetadata.email,
      requestedAt: imageMetadata.requestedAt.toISOString(),
      completedAt: completedAt,
    };
  }

  /** Marks an image as generated by setting the completedAt property. */
  public async markCompleted(imageId: string) {
    const imageMetadata = await this.getById(imageId);

    imageMetadata.completedAt = new Date();

    const dynamoItem = this.toDynamoItem(imageMetadata);
    const command = new PutCommand({
      TableName: this.config.imageMetadataTableName,
      Item: dynamoItem,
    });
    await this.dynamoDBDocumentClient.send(command);

    return imageMetadata;
  }

  private async getById(imageId: string) {
    const input = {
      TableName: this.config.imageMetadataTableName,
      Key: {
        imageId,
      },
    };
    const command = new GetCommand(input);
    const response = await this.dynamoDBDocumentClient.send(command);
    const item = response.Item;

    if (!item) {
      throw new Error(`No item found with imageId ${imageId}`);
    }

    const completedAt = item.completedAt ? new Date(item.completedAt) : null;

    const image: ImageMetadataEntity = {
      imageId: item.imageId,
      prompt: item.prompt,
      userId: item.userId,
      email: item.email,
      requestedAt: new Date(item.requestedAt),
      completedAt: completedAt,
    };

    return image;
  }
}
